version: "3.3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    # container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode_1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    # container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode_2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

#Use http://<server>:8088/filebrowser/ to acces filebrowser
  filebrowser:
     build:
         context: ./hue
         dockerfile: Dockerfile
     image: hdfs-filebrowser-adapted:3.11
     hostname: filebrowser
     container_name: filebrowser
     environment:
       - NAMENODE_HOST=namenode
       - NAMENODE_PORT=9870
     ports:
       - "8088:8088"
  
volumes:
  hadoop_namenode:
  hadoop_datanode_1:
  hadoop_datanode_2:
  
networks:
  default:
      external: 
         name: "bigdata-spielwiese-network"
